function BCI_Error(msg, title)

gScheme = load('Scheme.mat');
W = 300; H = 150;
sz = get(0, 'ScreenSize');
SW = sz(3); SH = sz(4);

%create the error dialog window
errDlg = uifigure("Name",title,"Color",gScheme.Window.BackgroundColor.Value,...
    "WindowStyle","alwaysontop",...
   "MenuBar","none",...
   "ToolBar","none",...
   'Resize', 'off');
errDlg.Position = [(SW-W)/2, (SH-H)/2, W, H];

uilabel(errDlg,...
    'FontName',gScheme.Label.Font.Value,...
    'FontSize',12,...
    'FontColor',gScheme.Label.FontColor.Value,...
    'Text', msg, ...
    'WordWrap','on',...
    'Position', [90,80,210,60],...
    'VerticalAlignment','bottom',...
    'HorizontalAlignment','left');

%create the OK button
uibutton(errDlg, "BackgroundColor",gScheme.Button.BackgroundColor.Value,...
    'Text','OK','FontSize', gScheme.Button.FontSize.Value,...
    'FontName', gScheme.Button.Font.Value,...
    'FontColor', gScheme.Button.FontColor.Value,...
    'Position',[110, 20, 80, 30], ...
    'ButtonPushedFcn',{@callback_close, errDlg});

uiimage(errDlg,"ImageSource","error_icon.png",...
    'Position',[10,50,70,70]);
end
function callback_close(~,~,fig)
    close(fig)
end